version: '3'
services:
  notification:
    container_name: notifications
    build:
      dockerfile: Dockerfile
      context: ./
    image: olakara/notifications
    ports:
      - "5000:80"
    depends_on:
      - notification-db
      - rabbitmq
  notification-db:
    container_name: notification-db
    image: mongo
    restart: always
    command: mongod --port 27072
    volumes:
      - ../mongo-volume-notifications:/data/db
    ports:
      - "27072:27072"
  rabbitmq:
    container_name: my-rabbit
    image: rabbitmq:3-management
    ports:
      - "8080:15672"
      - "5672:5672"
    volumes:
      - ../rabbitmq-volume/data:/var/lib/rabbitmq/
      - ../rabbitmq-volume/log:/var/log/rabbitmq/